version: '2'
services:
    db:
        image: mysql
        ports:
            - "3308:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
            XDEBUG_CONFIG: remote_host=192.168.1.3
            PHP_IDE_CONFIG: "serverName=skeleton.test"
            SYMFONY_BASE_HOST: skeleton.test
            CLEARDB_DATABASE_URL: mysql://dbuser:123@mysql/skeleton?reconnect=true
            SYMFONY_APP_SECRET: appScreetet
    php:
        build: ./docker/php-fpm
        ports:
            - "9000:9000"
        volumes:
            - .:/var/www:cached
        links:
            - db
    nginx:
        build: ./docker/nginx
        ports:
            - "80:80"
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx:cached
